base:
  d_node_feats: 138
  d_edge_feats: 14
  d_g_feats: 768
  d_cl_feats: 256
  d_hpath_ratio: 12
  n_mol_layers: 12
  path_length: 5
  n_heads: 12
  n_ffn_dense_layers: 2
  input_drop: 0.0
  attn_drop: 0.1
  feat_drop: 0.1
  batch_size: 288
  lr: 0.0002
  weight_decay: 0.000001
  candi_rate: 0.5
  fp_disturb_rate: 0.5
  md_disturb_rate: 0.5
  max_mrus: 3
